services:
  db:
    image: postgis/postgis:16-3.4
    container_name: senti_port_db
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/baza.sql:/docker-entrypoint-initdb.d/baza.sql

  web:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
    container_name: senti_port_backend
    volumes:
      - ../backend:/workspace
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: >
      bash -c "python scripts/wait_for_db.py && python scripts/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: sentiport.pl
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
    environment:
      - DMS_DEBUG=0
      - PERMIT_DOCKER=connected-networks
      - SSL_TYPE=self-signed
      - SPOOF_PROTECTION=0
      - ENABLE_POSTFIX_ACCOUNT_MAPPING=1
      - HOSTNAME=mail
      - DOMAINNAME=sentiport.pl
    volumes:
      - mail_data:/var/mail
      - ../docker/config:/tmp/docker-mailserver

volumes:
  postgres_data:
  mail_data:
  mail_config: